### ISSUE TITLE
Different output from nn~ in Max and TensorBoard preview

### ISSUE THREAD

**Issue by schmolmo** [acids-ircam/RAVE#158]
Hey there, 

after  training a model with 14h of Eliane Radigues’ work for about 1.000.000 steps, I’ve encountered an issue: The preview in the TensorBoard-Audio tab sound very promising, but when I download the model and use it in Max with the nn~ object, the output becomes very stutter-y. Do you have any idea why that could be the case?

I've attached some data for you to check out: [download link](https://cloud.wanubale.com/index.php/s/2CbLbAbm5ot328y)
- audio files named "orig_*" which is what I fed into the model
- audio files named "tensorboard_*" which is the tensorboard preview (cut into pieces)
- audio files named "nn_*" which is the output of the nn~ object (in "forward" mode) when it's fed with the corresponding input material (orig_0 and so on...)
- the model-file rave_radigue01.ts

I'd be super happy for any tips!
Thank you for all your efforts contributing to RAVE!

All best,
moritz

**Comment by wwerkk** [comment]
Recalling from my previous experiences with training attempts on drone music (ie. Well Tuned Piano) RAVE would not manage so well with sustained combination tones in which phase relationships matter quite a lot, especially when used in real-time.

If I recall correctly, nn~ forgets the contents of a buffer once it has been decoded, and obviously cannot foresee the future. The length of a buffer even if you're running on say, 2048 signal vector size in Max, is still only ~40ms.
In case of long, sustained note that changes subtly over a long period of time, you can intuitively grasp it would be an issue to tell, where are you in it, as the only thing that's happening is the overtone interactions (I would guess if you look at the spectrum of it, it might seem almost the same for a while), and also you're constantly forgetting what's just happened.

Have you tried using the model in offline mode ie. with the reconstruct.py script?

I guess this would be an interesting topic to talk about on the forum, I'm also curious if anyone had approached this kind of issue successfully, changing the default parameter ``n_signal=65536`` or otherwise.

**Comment by caillonantoine** [comment]
Hi, thanks for this issue,

Can you confirm you have exported your model with the realtime mode set to on ? Normally there isn't any difference between realtime and offline processing, as buffer are never forgotten but rather cached for the next computation. 

If you have indeed exported your model in realtime mode, it could be a bug on my side though.

Tell me :)

**Comment by FirestName** [comment]
Chiming in to raport having experienced a similar kinda issue, where a trained model on top of being unable to remain silent (constant hissing and clicking or so) and the output being stuttery as described by [schmolmo]. The model trained was the with the large settings and well, the dataset consisted of sounds that the model isn't supposed to handle well (ambient sounds etc.). My experiment was also trained to around 1000000 steps. Also, the model was indeed exported with in realtime mode. Also them tensorboard samples sounded mighty fine. 

Perhaps worth noting is that the model was already decent, but I decided to further supplement (and remove some audio) the dataset. Following this I reverted the training back to the first stage (for sufficient amount of steps) before proceeding with the second phase. I dunno if this is good practice. 

I personally blamed cicada recordings in the dataset, but removing those helped only very slightly and maybe merely resulted from the further training.

Best regards
Firest

**Comment by schmolmo** [comment]
Thank you all so much for the feedback and the tips, I'll try them all and get back to you beginning next week :~) 

best,
moritz

**Comment by FirestName** [comment]
Ok, now this is embarrassing. I re-exported my rave model today and viola, no more stuttering. However the model is still chirping even when it should be quiet, although I bet that's due to the dataset. 

I wonder what I've done incorrectly in the past since, when retracing I had indeed used them cached convolutions when exporting etc. (!python export_rave.py --run /content/drive/MyDrive/RAVE/RAVE/runs/suomisaundi/rave/version_48/checkpoints/last.ckpt --cached true --name suomisaundi_rt)

Only difference I can think of is that this time I used that miniconda environment.
Yet, as I bet that this doesn't explain the "issue", I must condone to simply somehow not having exported with real time mode...

**Comment by caillonantoine** [comment]
Tbh it can be quite confusing... Normally it should be easier know :)

**Comment by FirestName** [comment]
Yeah, seems so. 
However, that high pitched chirping is still present with nn~ (both when running with prior and when feeding with encoder) while not in the reconstruct.py generations?

**Comment by schmolmo** [comment]
Thank you so much for the tip with the --cached flag (which is now --streaming in v2 I suppose), the stuttering is gone now :-)

**Comment by moiseshorta** [comment]
@FirestName I've experienced this high pitched 'chirping' before, especially when the model has been 'overtrained' (usually going beyond 3.5M steps. I'm not sure if this is an artefact of the model trying to learn some kind of human-inaudible artefacts, but I've heard it consistently when 'overtraining'. 

Question to you: did you try to augment your dataset with the provided `resample` function?

**Comment by FirestName** [comment]
@moiseshorta oh, if this is the case, then my model is well "overtrained"... and that's a bummer. 

Wonder if those artefacts result from lossy to lossless conversion (or just mp3 compression artefacts the model is learning)?

Yes, I did augment my dataset.

**Comment by moiseshorta** [comment]
Yes, seems like if you used the provided data aug took, it might have introduced artifacts due to resampling? 

I really recommend backing up checkpoints when training goes into phase 2, since when in Adversarial loss, more training doesn't necessarily lead to better results. Hope this helps!

**Comment by FirestName** [comment]
You've had better results with extensive/longer trainings with unaugmented datasets (i.e. without resampling)?

**Comment by moiseshorta** [comment]
@FirestName Yes, I've found that using other audio data augmentation libraries and effects (audio normalization, phase inversion) can help with better learning the dataset. I recommend audiomentations or pedalboard.

**Comment by FirestName** [comment]
> 

BTW may I inquire an estimate about how many epochs in have those trainings been where you've observed that degradation starting to kick in?

**Comment by moiseshorta** [comment]
> @moiseshorta BTW may I inquire an estimate about how many epochs in have those trainings been where you've observed that degradation starting to kick in?

If I remember correctly, the degradation started happening after the second phase of training kicked in, aprox. 1Million steps.
